import { Link } from 'wouter';
import { Button } from '../components/ui/button';
import { Card } from '../components/ui/card';
import { Lightbulb, Magnet, Hash, Menu } from 'lucide-react';

const pillars = [
  { icon: Magnet, title: '钩子 Hook', desc: '在 3 秒内抓住注意力', points: ['反直觉开场', '结果先行', '情绪拉满'] },
  { icon: Lightbulb, title: '痛点拆解', desc: '把用户焦虑讲到心里', points: ['问题具象化', '场景化表达', '提供路径'] },
  { icon: Hash, title: '话题策略', desc: '让流量精准触达', points: ['行业大词', '核心诉求', '搜索词组合'] },
];

export default function Home() {
  return <main className="text-gray-900"><header className="fixed inset-x-0 top-0 z-50 border-b bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between p-4"><div className="font-bold text-blue-800">Viral Script Guide</div><nav className="hidden gap-6 sm:flex"><a href="#framework" className="hover:underline">框架</a><a href="#tools" className="hover:underline">工具</a><Link href="/case-study" className="hover:underline">案例</Link></nav><Button aria-label="立即开始">立即开始</Button><button className="sm:hidden" aria-label="打开菜单"><Menu /></button></div></header>
  <section className="mx-auto grid max-w-7xl gap-8 px-4 pb-20 pt-32 lg:grid-cols-2"><div><h1 className="text-4xl font-extrabold text-blue-800 md:text-5xl">学会创作爆款脚本</h1><p className="mt-4 text-gray-600">掌握 Hook、Pain Points、Hashtag Strategy 三大支柱，把灵感变成高转化短视频。</p><div className="mt-6 flex gap-3"><Link href="/script-builder"><Button>打开脚本构建器</Button></Link><Link href="/case-study"><Button className="bg-orange-500 hover:bg-orange-600">查看案例拆解</Button></Link></div><div className="mt-8 grid grid-cols-3 gap-4 text-center"><Card><div className="text-2xl font-bold text-blue-700">7,754</div><p className="text-sm text-gray-500">点赞</p></Card><Card><div className="text-2xl font-bold text-blue-700">5,510</div><p className="text-sm text-gray-500">转发</p></Card><Card><div className="text-2xl font-bold text-blue-700">3</div><p className="text-sm text-gray-500">核心要素</p></Card></div></div><img className="h-full w-full rounded-3xl object-cover" src="https://images.unsplash.com/photo-1518773553398-650c184e0bb3?auto=format&fit=crop&w=1200&q=80" alt="蓝色科技背景" /></section>
  <section id="framework" className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-3xl font-bold">三大支柱框架</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{pillars.map((item) => <Card key={item.title} className="transition hover:bg-blue-50 hover:shadow-lg"><item.icon className="text-blue-700" /><h3 className="mt-3 text-xl font-semibold">{item.title}</h3><p className="mt-2 text-sm text-gray-600">{item.desc}</p><ul className="mt-3 list-disc pl-5 text-sm text-gray-700">{item.points.map((p) => <li key={p}>{p}</li>)}</ul></Card>)}</div><img src="https://images.unsplash.com/photo-1551281044-8b4b6ce6c9bf?auto=format&fit=crop&w=800&q=80" alt="三大支柱示意图" className="mt-8 w-full rounded-2xl" /></section>
  <section className="mx-auto max-w-7xl px-4 py-16"><Card><img src="https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=1000&q=80" className="rounded-xl" /><div className="mt-4 grid gap-4 md:grid-cols-2"><Card><h3 className="font-semibold">关键洞察</h3><ul className="mt-2 list-disc pl-5 text-sm"><li>开场先给结果</li><li>痛点连击强化共鸣</li><li>镜头切换提升留存</li><li>标签匹配搜索意图</li></ul></Card><Card><h3 className="font-semibold">应用模式</h3><p className="mt-2 text-sm">套用 5 段式模板即可快速起稿。</p></Card></div></Card></section>
  <section id="tools" className="mx-auto max-w-7xl px-4 py-16"><Card className="text-center"><img src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1000&q=80" className="mx-auto rounded-xl" /><div className="mt-6"><Link href="/script-builder"><Button className="px-8">前往完整脚本构建器</Button></Link></div></Card></section>
  <section className="bg-gradient-to-r from-blue-700 to-blue-500 py-16 text-center text-white"><h2 className="text-3xl font-bold">把下一条视频做成爆款</h2><p className="mt-3 text-blue-50">立即使用模板化创作流程，提升完播与互动率。</p><Link href="/script-builder"><Button className="mt-6 bg-orange-500 hover:bg-orange-600">马上创作</Button></Link></section>
  <footer className="mx-auto grid max-w-7xl gap-8 px-4 py-16 text-sm text-gray-600 md:grid-cols-4"><div><h4 className="font-semibold text-gray-900">关于</h4></div><div><h4 className="font-semibold text-gray-900">资源</h4></div><div><h4 className="font-semibold text-gray-900">社区</h4></div><div><h4 className="font-semibold text-gray-900">关注</h4></div><div className="md:col-span-4">© 2026 Viral Script Guide</div></footer></main>;
}
